#!/usr/bin/env python
# -*- coding: utf-8 -*-

from DB2Rest.db2rest import LoadModelClasses
import os


if __name__ == '__main__':
    CONFIG_FILE = os.environ['CONFIG_FILE']
    load_models = LoadModelClasses(CONFIG_FILE)
    load_models.generate_file()
